[1;31m[ERROR][0;39m [2014-04-09 18:04:28,402] [c.tcbook.ws.database.datasource.DataSourceManager->initDataSource] [DataSourceManager.java:96] [Exception Problem on create database connection pool (DataSource):  - Thread ID main - Start]
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' (using password: YES))
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: java.sql.SQLException: Access denied for user 'tcbook-ws'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception Problem on create database connection pool (DataSource):  - End]
[1;31m[ERROR][0;39m [2014-04-09 18:04:28,443] [com.tcbook.ws.bin.TCBookMain->start] [TCBookMain.java:69] [Exception [TCBook] Error initializing database! TCBookMain will not start! - Thread ID main - Start]
java.lang.RuntimeException: Problem on create database connection pool (DataSource)
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:99) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' (using password: YES))
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	... 2 common frames omitted
Caused by: java.sql.SQLException: Access denied for user 'tcbook-ws'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception [TCBook] Error initializing database! TCBookMain will not start! - End]
[1;31m[ERROR][0;39m [2014-04-09 18:04:28,445] [com.tcbook.ws.bin.TCBookMain->start] [TCBookMain.java:88] [Exception Error starting TCBookMain  - Thread ID main - Start]
java.lang.RuntimeException: Problem on create database connection pool (DataSource)
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:99) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' (using password: YES))
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	... 2 common frames omitted
Caused by: java.sql.SQLException: Access denied for user 'tcbook-ws'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception Error starting TCBookMain  - End]
[1;31m[ERROR][0;39m [2014-04-09 18:04:47,701] [c.tcbook.ws.database.datasource.DataSourceManager->initDataSource] [DataSourceManager.java:96] [Exception Problem on create database connection pool (DataSource):  - Thread ID main - Start]
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' (using password: YES))
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: java.sql.SQLException: Access denied for user 'tcbook-ws'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception Problem on create database connection pool (DataSource):  - End]
[1;31m[ERROR][0;39m [2014-04-09 18:04:47,713] [com.tcbook.ws.bin.TCBookMain->start] [TCBookMain.java:69] [Exception [TCBook] Error initializing database! TCBookMain will not start! - Thread ID main - Start]
java.lang.RuntimeException: Problem on create database connection pool (DataSource)
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:99) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' (using password: YES))
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	... 2 common frames omitted
Caused by: java.sql.SQLException: Access denied for user 'tcbook-ws'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception [TCBook] Error initializing database! TCBookMain will not start! - End]
[1;31m[ERROR][0;39m [2014-04-09 18:04:47,714] [com.tcbook.ws.bin.TCBookMain->start] [TCBookMain.java:88] [Exception Error starting TCBookMain  - Thread ID main - Start]
java.lang.RuntimeException: Problem on create database connection pool (DataSource)
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:99) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' (using password: YES))
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	... 2 common frames omitted
Caused by: java.sql.SQLException: Access denied for user 'tcbook-ws'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception Error starting TCBookMain  - End]
[1;31m[ERROR][0;39m [2014-04-09 18:05:16,167] [c.tcbook.ws.database.datasource.DataSourceManager->initDataSource] [DataSourceManager.java:96] [Exception Problem on create database connection pool (DataSource):  - Thread ID main - Start]
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' (using password: YES))
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: java.sql.SQLException: Access denied for user 'tcbook-ws'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception Problem on create database connection pool (DataSource):  - End]
[1;31m[ERROR][0;39m [2014-04-09 18:05:24,997] [com.tcbook.ws.bin.TCBookMain->start] [TCBookMain.java:69] [Exception [TCBook] Error initializing database! TCBookMain will not start! - Thread ID main - Start]
java.lang.RuntimeException: Problem on create database connection pool (DataSource)
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:99) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' (using password: YES))
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	... 2 common frames omitted
Caused by: java.sql.SQLException: Access denied for user 'tcbook-ws'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception [TCBook] Error initializing database! TCBookMain will not start! - End]
[1;31m[ERROR][0;39m [2014-04-09 18:05:24,998] [com.tcbook.ws.bin.TCBookMain->start] [TCBookMain.java:88] [Exception Error starting TCBookMain  - Thread ID main - Start]
java.lang.RuntimeException: Problem on create database connection pool (DataSource)
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:99) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' (using password: YES))
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	... 2 common frames omitted
Caused by: java.sql.SQLException: Access denied for user 'tcbook-ws'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception Error starting TCBookMain  - End]
[1;31m[ERROR][0;39m [2014-04-09 18:07:23,679] [c.tcbook.ws.database.datasource.DataSourceManager->initDataSource] [DataSourceManager.java:96] [Exception Problem on create database connection pool (DataSource):  - Thread ID main - Start]
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' to database 'mc536')
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'tcbook-ws'@'localhost' to database 'mc536'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception Problem on create database connection pool (DataSource):  - End]
[1;31m[ERROR][0;39m [2014-04-09 18:08:19,553] [com.tcbook.ws.bin.TCBookMain->start] [TCBookMain.java:69] [Exception [TCBook] Error initializing database! TCBookMain will not start! - Thread ID main - Start]
java.lang.RuntimeException: Problem on create database connection pool (DataSource)
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:99) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' to database 'mc536')
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	... 2 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'tcbook-ws'@'localhost' to database 'mc536'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception [TCBook] Error initializing database! TCBookMain will not start! - End]
[1;31m[ERROR][0;39m [2014-04-09 18:08:19,556] [com.tcbook.ws.bin.TCBookMain->start] [TCBookMain.java:88] [Exception Error starting TCBookMain  - Thread ID main - Start]
java.lang.RuntimeException: Problem on create database connection pool (DataSource)
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:99) ~[bin/:na]
	at com.tcbook.ws.bin.TCBookMain.start(TCBookMain.java:67) [bin/:na]
	at com.tcbook.ws.bin.TCBookMain.main(TCBookMain.java:36) [bin/:na]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'tcbook-ws'@'localhost' to database 'mc536')
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getLogWriter(BasicDataSource.java:1098) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:350) ~[commons-dbcp-1.4.jar:1.4]
	at com.tcbook.ws.database.datasource.DataSourceManager.initDataSource(DataSourceManager.java:84) ~[bin/:na]
	... 2 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'tcbook-ws'@'localhost' to database 'mc536'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334) ~[mysql-connector-java-5.1.22-bin.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 6 common frames omitted

[Exception Error starting TCBookMain  - End]
[1;31m[ERROR][0;39m [2014-04-09 18:43:22,848] [com.tcbook.ws.web.manager.WebServerManager->startServer] [WebServerManager.java:68] [Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - Thread ID WebServerManager - Start]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind(Native Method) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:124) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:59) ~[na:1.6.0_45]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:197) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:362) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:275) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.Server.doStart(Server.java:254) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at com.tcbook.ws.web.manager.WebServerManager.startServer(WebServerManager.java:63) [bin/:na]
	at com.tcbook.ws.web.manager.WebServerManager.run(WebServerManager.java:33) [bin/:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]

[Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - End]
[1;31m[ERROR][0;39m [2014-04-09 18:45:39,159] [com.tcbook.ws.web.manager.WebServerManager->startServer] [WebServerManager.java:68] [Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - Thread ID WebServerManager - Start]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind(Native Method) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:124) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:59) ~[na:1.6.0_45]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:197) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:362) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:275) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.Server.doStart(Server.java:254) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at com.tcbook.ws.web.manager.WebServerManager.startServer(WebServerManager.java:63) [bin/:na]
	at com.tcbook.ws.web.manager.WebServerManager.run(WebServerManager.java:33) [bin/:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]

[Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - End]
[1;31m[ERROR][0;39m [2014-04-09 18:46:04,492] [com.tcbook.ws.web.manager.WebServerManager->startServer] [WebServerManager.java:68] [Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - Thread ID WebServerManager - Start]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind(Native Method) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:124) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:59) ~[na:1.6.0_45]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:197) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:362) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:275) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.Server.doStart(Server.java:254) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at com.tcbook.ws.web.manager.WebServerManager.startServer(WebServerManager.java:63) [bin/:na]
	at com.tcbook.ws.web.manager.WebServerManager.run(WebServerManager.java:33) [bin/:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]

[Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - End]
[1;31m[ERROR][0;39m [2014-04-09 21:36:46,765] [com.tcbook.ws.web.manager.WebServerManager->startServer] [WebServerManager.java:68] [Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - Thread ID WebServerManager - Start]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind(Native Method) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:124) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:59) ~[na:1.6.0_45]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:197) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:362) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:275) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.Server.doStart(Server.java:254) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at com.tcbook.ws.web.manager.WebServerManager.startServer(WebServerManager.java:63) [bin/:na]
	at com.tcbook.ws.web.manager.WebServerManager.run(WebServerManager.java:33) [bin/:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]

[Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - End]
[1;31m[ERROR][0;39m [2014-04-09 21:37:09,115] [com.tcbook.ws.web.manager.WebServerManager->startServer] [WebServerManager.java:68] [Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - Thread ID WebServerManager - Start]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind(Native Method) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:124) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:59) ~[na:1.6.0_45]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:197) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:362) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:275) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.Server.doStart(Server.java:254) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at com.tcbook.ws.web.manager.WebServerManager.startServer(WebServerManager.java:63) [bin/:na]
	at com.tcbook.ws.web.manager.WebServerManager.run(WebServerManager.java:33) [bin/:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]

[Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - End]
[1;31m[ERROR][0;39m [2014-04-09 22:00:21,160] [com.tcbook.ws.web.manager.WebServerManager->startServer] [WebServerManager.java:68] [Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - Thread ID WebServerManager - Start]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind(Native Method) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:124) ~[na:1.6.0_45]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:59) ~[na:1.6.0_45]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:197) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:362) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:275) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.server.Server.doStart(Server.java:254) ~[jetty-server-7.2.2.v20101205.jar:7.2.2.v20101205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) ~[jetty-util-7.2.2.v20101205.jar:7.2.2.v20101205]
	at com.tcbook.ws.web.manager.WebServerManager.startServer(WebServerManager.java:63) [bin/:na]
	at com.tcbook.ws.web.manager.WebServerManager.run(WebServerManager.java:33) [bin/:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]

[Exception [WEB_SERVER_MANAGER] Error starting Jetty webserver  - End]
